# Generated by Django 5.0.7 on 2025-01-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_authuser_pesel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'permissions': (('can_see_patient_page', 'Can see patient page'),)},
        ),
    ]
