# Generated by Django 5.0.7 on 2024-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_visit_medicaldocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='pesel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
