# Generated by Django 5.0.7 on 2025-01-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'permissions': (('can_see_patient_page', 'Can see patient page'), ('can_see_system_page', 'Can see system page'))},
        ),
    ]
