# Generated by Django 5.0.7 on 2024-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_authuser_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_visit_finished',
            field=models.BooleanField(default=False),
        ),
    ]
