# Generated by Django 5.0.7 on 2024-12-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_medicaldocumentation_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorspecialization',
            options={'permissions': (('can_add_specialization', 'Can add specialization'), ('can_edit_specialization', 'Can edit specialization'), ('can_delete_specialization', 'Can delete specialization'), ('can_get_specialization', 'Can get specialization')), 'verbose_name': 'DoctorSpecialization', 'verbose_name_plural': 'DoctorSpecializations'},
        ),
        migrations.AlterModelOptions(
            name='medicaldocumentation',
            options={'permissions': (('can_add_medical_documentation', 'Can add medical documentation'), ('can_edit_medical_documentation', 'Can edit medical documentation'), ('can_delete_medical_documentation', 'Can delete medical documentation'), ('can_get_medical_documentation', 'Can get medical documentation')), 'verbose_name': 'Medical Documentation', 'verbose_name_plural': 'Medical Documentations'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'permissions': (('can_add_visit', 'Can add visit'), ('can_edit_visit', 'Can edit visit'), ('can_delete_visit', 'Can delete visit'), ('can_get_visit', 'Can get visit')), 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
