# Generated by Django 5.0.7 on 2025-01-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_doctorspecialization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctordetails',
            options={'permissions': (('can_see_doctor_page', 'Can see doctor page'),), 'verbose_name': 'DoctorDetail', 'verbose_name_plural': 'DoctorDetails'},
        ),
    ]
